### ISSUE TITLE
events with bytes don't work

### ISSUE THREAD

**Issue by Georgi87** [ethereum/pyethereum#342]
Executing `createMarket` in this code:

```
event LogBytes(bytes);

function createMarket(bytes32 eventHash, uint fee, uint initialFunding, address makerAddress) returns (bytes32) {
        LogBytes(msg.data);
        return MarketLibrary.createMarket(data, MIN_MARKET_BALANCE, eventHash, fee, initialFunding, makerAddress);
    }
```

Will result in an error:

```
Traceback (most recent call last):
  File "contracts/tests/test_buy_shares.py", line 20, in test
    market_hash = self.market_contract.createMarket(event_hash, fee, initial_funding, self.lmsr_contract.address, value=value)
  File "/vagrant/src/pyethereum/ethereum/tester.py", line 111, in kall
    **dict_without(kwargs, 'sender', 'value', 'output'))
  File "/vagrant/src/pyethereum/ethereum/tester.py", line 212, in _send
    (s, o) = pb.apply_transaction(self.block, tx)
  File "/vagrant/src/pyethereum/ethereum/processblock.py", line 166, in apply_transaction
    result, gas_remained, data = apply_msg(ext, message)
  File "/vagrant/src/pyethereum/ethereum/processblock.py", line 249, in apply_msg
    return _apply_msg(ext, msg, ext.get_code(msg.code_address))
  File "/vagrant/src/pyethereum/ethereum/processblock.py", line 277, in _apply_msg
    res, gas, dat = vm.vm_execute(ext, msg, code)
  File "/vagrant/src/pyethereum/ethereum/vm.py", line 488, in vm_execute
    ext.log(msg.to, topics, data)
  File "/vagrant/src/pyethereum/ethereum/processblock.py", line 239, in <lambda>
    block.add_log(Log(addr, topics, data))
  File "/vagrant/src/pyethereum/ethereum/blocks.py", line 993, in add_log
    L(log)
  File "/vagrant/src/pyethereum/ethereum/tester.py", line 96, in <lambda>
    listener = lambda log: self._translator.listen(log, noprint=False)
  File "/vagrant/src/pyethereum/ethereum/abi.py", line 115, in listen
    deserialized_args = decode_abi(unindexed_types, log.data)
  File "/vagrant/src/pyethereum/ethereum/abi.py", line 439, in decode_abi
    return [dec(proctypes[i], outs[i]) for i in range(len(outs))]
  File "/vagrant/src/pyethereum/ethereum/abi.py", line 449, in dec
    assert len(arg[32:]) == ceil32(L), "Wrong data size for string/bytes object"
AssertionError: Wrong data size for string/bytes object
```

**Comment by Georgi87** [comment]
Commenting out the assert statement fixed the issue:
File: abi.py L449
`# assert len(arg[32:]) == ceil32(L), "Wrong data size for string/bytes object"`

**Comment by pipermerriam** [comment]
This should really be fixed in the `listen` function.  When it extracts the types it should convert all of the `bytes/string` types to `bytes32` types since log statements that include `bytes/string` arguments log the `sha3` of those values (if I remember correctly how logging works).

See this part of the code.  https://github.com/ethereum/pyethereum/blob/develop/ethereum/abi.py#L223

**Comment by miladmostavi** [comment]
Any news on this issue? @Georgi87's workaround did work for me. But hard to debug the issue.

**Comment by joeykrug** [comment]
No longer an issue on latest

**Comment by joeykrug** [comment]
Actually, nvm still an issue.

What needs to change wrt listening?
